

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  error = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r}
library(tidyverse)
library(tidymodels)
library(gstat)
library(sp)
library(openxlsx)
library(readxl)
library(raster)
library(rstudioapi)
library(sp)
source("../../R/my-functions.R")
```


# Aprendizado de Máquina

### Definindo o plano de multisession
```{r}
future::plan("multisession")
```

### Lendo a base

```{r}
data_set <- read_rds("../../data/base_krigagem.rds") %>% 
  mutate(year = as.numeric(year))
```





```{r}
years <- data_set %>% pull(year) %>% unique()
for(i in seq_along(years)){
  my_year <- years[i]
  df <- data_set %>% 
    filter(year == my_year)
  xco2_initial_split <- initial_split(
    df %>% 
      ungroup() %>% 
      dplyr::select(lai:xco2) #%>% 
      # sample_n(trunc(nrow(df)*.01289))
    , 
    prop = 0.75)
  xco2_train <- training(xco2_initial_split)
  xco2_test <- testing(xco2_initial_split)
  xco2_resamples <- vfold_cv(xco2_train, v = 5)
  
  hist_xco2 <- xco2_train  %>%
    ggplot(aes(x=xco2, y=..density..))+
    geom_histogram(bins = 30, 
                   color="black",  
                   fill="lightgray")+
    geom_density(alpha=.05,fill="red")+
    theme_bw() +
    labs(x="Xco2", y = "Densidade",title = my_year)
  print(hist_xco2)
  
  xco2_train   %>%
    dplyr::select(where(is.numeric)) %>%
    drop_na() %>%
    cor()  %>%
    corrplot::corrplot()
  
  xco2_recipe <- recipe(xco2 ~ ., 
                        data = xco2_train) %>%  
    step_normalize(all_numeric_predictors())  %>% 
    step_novel(all_nominal_predictors()) %>% 
    step_zv(all_predictors())
  bake(prep(xco2_recipe), new_data = NULL)
  
  ### Definição do modelo
  xco2_rf_model <- rand_forest(
    min_n = tune(),
    mtry = tune(),
    trees = tune()
  )   %>%  
    set_mode("regression")  %>% 
    set_engine("randomForest")
  
  ### Workflow
  xco2_rf_wf <- workflow()   %>%  
    add_model(xco2_rf_model) %>%  
    add_recipe(xco2_recipe)
  
  grid_rf <- expand.grid(
    min_n = c(5, 10, 20),
    mtry =  c(2, 4),
    trees = c(100, 300) #<-----------------------
  )
  xco2_rf_tune_grid <- tune_grid(
    xco2_rf_wf,
    resamples = xco2_resamples,
    grid = grid_rf,
    metrics = metric_set(rmse)
  )
  print(autoplot(xco2_rf_tune_grid) +
             labs(title = my_year))
  collect_metrics(xco2_rf_tune_grid)
  xco2_rf_tune_grid %>%   show_best(metric = "rmse", n = 6)

  xco2_rf_best_params <- select_best(xco2_rf_tune_grid, "rmse")
  xco2_rf_wf <- xco2_rf_wf %>% finalize_workflow(xco2_rf_best_params)
  xco2_rf_last_fit <- last_fit(xco2_rf_wf, xco2_initial_split)

  xco2_test_preds <- bind_rows(
    collect_predictions(xco2_rf_last_fit)  %>%   
      mutate(modelo = "rf")
  )
  
  pre_obs_plot <- xco2_test_preds %>% 
    ggplot(aes(x=.pred, y=xco2)) +
    geom_point()+
    theme_bw() +
    geom_smooth(method = "lm") +
    ggpubr::stat_regline_equation(ggplot2::aes(
      label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~"))) +
    geom_abline (slope=1, linetype = "dashed", color="Red") +
    labs(title = my_year)
  print(pre_obs_plot)
  
  xco2_modelo_final <- xco2_rf_wf %>% fit(df)
  saveRDS(xco2_modelo_final,
          paste0("models/xco2_modelo_rf_",my_year,".rds"))
  xco2_rf_last_fit_model <- xco2_rf_last_fit$.workflow[[1]]$fit$fit
  
  
  vip::vip(xco2_rf_last_fit_model,
           aesthetics = list(color = "black", fill = "orange")) +
    theme(axis.text.y=element_text(size=rel(1.5)),
          axis.text.x=element_text(size=rel(1.5)),
          axis.title.x=element_text(size=rel(1.5))
    )
  da <- xco2_test_preds %>% 
    filter(xco2 > 0, .pred>0 )
  
  my_r <- cor(da$xco2,da$.pred)
  my_r2 <- my_r*my_r
  my_mse <- Metrics::mse(da$xco2,da$.pred)
  my_rmse <- Metrics::rmse(da$xco2,
                           da$.pred)
  my_mae <- Metrics::mae(da$xco2,da$.pred)
  my_mape <- Metrics::mape(da$xco2,da$.pred)*100
  
  
  vector_of_metrics <- c(r=my_r, R2=my_r2, MSE=my_mse, RMSE=my_rmse, MAE=my_mae, MAPE=my_mape)
  print(data.frame(vector_of_metrics))
}
```
